### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by whiteyhat** [paranerd/MMORPG#1]
```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/whiteyhat/Desktop/MMORPG-master/node_modules/bson/ext/index.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/Users/whiteyhat/Desktop/MMORPG-master/node_modules/mongojs/index.js:548
    var p = Proxy.create({
                  ^

TypeError: Proxy.create is not a function
    at Function.connect (/Users/whiteyhat/Desktop/MMORPG-master/node_modules/mongojs/index.js:548:19)
    at Object.<anonymous> (/Users/whiteyhat/Desktop/MMORPG-master/game.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by paranerd** [comment]
Thanks for pointing out!
Moved from MongoJS to the official MongoDB-npm-package. That solved the problem.
